exports.inventario = [ {
    appid: 730,
    contextid: '2',
    assetid: '11274782820',
    classid: '1797256701',
    instanceid: '0',
    amount: 1,
    pos: 1,
    id: '11274782820',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYznarJJjkQ6ovjw4SPlfP3auqEl2oBuJB1j--WoY322QziqkdpZGr3IteLMlhpw4RJCv8',
    descriptions:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    tradable: true,
    name: 'Gamma Case',
    name_color: 'D2D2D2',
    type: 'Base Grade Container',
    market_name: 'Gamma Case',
    market_hash_name: 'Gamma Case',
    commodity: true,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '9977102029',
    classid: '1690096482',
    instanceid: '0',
    amount: 1,
    pos: 2,
    id: '9977102029',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYynaSdJGhE74y0wNWIw_OlNuvXkDpSuZQmi--SrN-h3gey-Uo6YWmlIoCLMlhplhFFvwI',
    descriptions:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    tradable: true,
    name: 'Chroma 3 Case',
    name_color: 'D2D2D2',
    type: 'Base Grade Container',
    market_name: 'Chroma 3 Case',
    market_hash_name: 'Chroma 3 Case',
    commodity: true,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '9835537757',
    classid: '1989316810',
    instanceid: '302028390',
    amount: 1,
    pos: 3,
    id: '9835537757',
    background_color: '',
    icon_url: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0r-eOF3j2azL7Ky7VEF96U7oKNT6M-TL2s-WXQzDNErl_S1pQf6IGpGNKaMqIOkA90YUP-mPhkRIzDhgvNMZJfACpx2EfJbQ1xDhPcZpVyCChuh8O9Sw',
    icon_url_large: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0r-eOF3j2azL7Ky7VEF96Iu8Pdz-M4Gek7bvCFzqYQbktSw0ELqVVpmNJPJ2LP0Y81NYLrz3slhV5R0R5K5wIYAG8jHccPbI3xTQeMcISxW39IpXe1FszoA9_3hE',
    descriptions: [ [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'Sealed Graffiti | Bling (Jungle Green)',
    name_color: 'D2D2D2',
    type: 'Base Grade Graffiti',
    market_name: 'Sealed Graffiti | Bling (Jungle Green)',
    market_hash_name: 'Sealed Graffiti | Bling (Jungle Green)',
    market_actions: [ [Object] ],
    commodity: true,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '9368154317',
    classid: '310779124',
    instanceid: '302028390',
    amount: 1,
    pos: 4,
    id: '9368154317',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhz3MzHfTRU6eO-kYGdjrmjau-EzzkGvcEnibjDotqiilKyrUY-MGDwJYOVIwNoYg7V-le8yLztm9bi63kWu9PZ',
    icon_url_large: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhz3MzHfTRU6eO-kYGdjsj4MqnWkyUGsZEk07uWoIijiwW2_EVrMT-lcoPHIQ89YF3Qq1TowrjqhZC-tc_L1zI97TFu1Ht6',
    descriptions: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'Tec-9 | Groundwater',
    name_color: 'D2D2D2',
    type: 'Consumer Grade Pistol',
    market_name: 'Tec-9 | Groundwater (Battle-Scarred)',
    market_hash_name: 'Tec-9 | Groundwater (Battle-Scarred)',
    market_actions: [ [Object] ],
    commodity: false,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '9037786662',
    classid: '310776577',
    instanceid: '302028390',
    amount: 1,
    pos: 5,
    id: '9037786662',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1Jf2-r3dTlS7ciJgZKJqPrxN7LEmyUEvZUj2biX8dvx2w3g-ENsYmDycoScclU-NFmG_wC-xOm815O-vs_I1zI97XEv6cYI',
    icon_url_large: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1Jf2-r3dTlS7ciJgZKJqPrxN7LEm1Rd6dd2j6eUoNyn2wXir0Q4YGD3J4aVcw8_N1rZ-gK-lO-5gMe8uZqam3dhuHIj-z-DyAPtZave',
    descriptions: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'UMP-45 | Urban DDPAT',
    name_color: 'D2D2D2',
    type: 'Consumer Grade SMG',
    market_name: 'UMP-45 | Urban DDPAT (Field-Tested)',
    market_hash_name: 'UMP-45 | Urban DDPAT (Field-Tested)',
    market_actions: [ [Object] ],
    commodity: false,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '8961339906',
    classid: '1989293638',
    instanceid: '302028390',
    amount: 1,
    pos: 6,
    id: '8961339906',
    background_color: '',
    icon_url: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0qe6yD3n-ZDLdYXKOTVxqTudcPGjZrGLx5ujCF2nASeh-EF9XdfEAo2JLNZiKahtv0oMVu2u_0UdyEhk6f9BKZAarxm1OM7xzkCNAHLIEtUY',
    icon_url_large: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0qe6yD3n-ZDLdEC3YDlltU-cLND7c92Hxt-SVFGqfFe54SgACdfcFoDJPP82AOBtrhdZZ-Ga9zhwzDhgvNMZJfACpx2EfJbQ1xDhPJ8pUkXbyR7BPMH0',
    descriptions: [ [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'Sealed Graffiti | Still Happy (Bazooka Pink)',
    name_color: 'D2D2D2',
    type: 'Base Grade Graffiti',
    market_name: 'Sealed Graffiti | Still Happy (Bazooka Pink)',
    market_hash_name: 'Sealed Graffiti | Still Happy (Bazooka Pink)',
    market_actions: [ [Object] ],
    commodity: true,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '8856238275',
    classid: '1989286213',
    instanceid: '302028390',
    amount: 1,
    pos: 7,
    id: '8856238275',
    background_color: '',
    icon_url: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0o_ePHnjyVzPBLiWXSgw9TrMMY2jbqGCm5OvCF27BF-4tRFtVfqoApzJNNc7YPRo60IQN8iuomUM7HRkkfddLZQOvw2QfKOBykHgWcJjdxwPgPQ',
    icon_url_large: 'IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdB2ozio1RrlIWFK3UfvMYB8UsvjiMXojflsZalyxSh31CIyHz2GZ-KuFpPsrTzBG0o_ePHnjyVzPBLiXmEF96GuZANGnRrGWt4uzHRTvNQOEuFwxSK_YF9jVLa8raOEE51oID_GbvkxYpS1g4fMIAcwC3xWYeJLExwTEePJZVkS2kI5er3rpUnw',
    descriptions: [ [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'Sealed Graffiti | Death Sentence (Battle Green)',
    name_color: 'D2D2D2',
    type: 'Base Grade Graffiti',
    market_name: 'Sealed Graffiti | Death Sentence (Battle Green)',
    market_hash_name: 'Sealed Graffiti | Death Sentence (Battle Green)',
    market_actions: [ [Object] ],
    commodity: true,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '8165004828',
    classid: '310776840',
    instanceid: '302028390',
    amount: 1,
    pos: 8,
    id: '8165004828',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbmkOVUw7ODHTi1P7-O7kYSCgvq6ZO2EwmlU6ZEji-qRoo6tigzk_xZpY2mmcI6RdVBrMFnV_FLslOy804j84so1c9KYww',
    icon_url_large: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbmkOVUw7ODHTi1P7-O7kYSCgvrLP7rDkW4fv5Mk3uvE9NiniVfk_BFkMWHzINOQcgZrNVDU_QfrkO_qg5Xu6Z-an2wj5HfSinewXQ',
    descriptions: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'SCAR-20 | Contractor',
    name_color: 'D2D2D2',
    type: 'Consumer Grade Sniper Rifle',
    market_name: 'SCAR-20 | Contractor (Field-Tested)',
    market_hash_name: 'SCAR-20 | Contractor (Field-Tested)',
    market_actions: [ [Object] ],
    commodity: false,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '5730540637',
    classid: '469444882',
    instanceid: '302028390',
    amount: 1,
    pos: 9,
    id: '5730540637',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszMdS1D-OOjhoK0mvLwOq7c2D4B6pwijLiXpt6s3lDkrkJvZG-hLI7Ee1M7YVmC8gO-kunrjZK1tJXXiSw0uDynv1g',
    icon_url_large: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszMdS1D-OOjhoK0mvLwOq7cqWdQ-sJ0xLyR99WmjgXi-EFlZT3zcYeWdQBsaVCB8wS7we-9jcS875rNwXZqsig8pSGKg7HJkhk',
    descriptions: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'Tec-9 | Urban DDPAT',
    name_color: 'D2D2D2',
    type: 'Consumer Grade Pistol',
    market_name: 'Tec-9 | Urban DDPAT (Field-Tested)',
    market_hash_name: 'Tec-9 | Urban DDPAT (Field-Tested)',
    market_actions: [ [Object] ],
    commodity: false,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] },
   {
    appid: 730,
    contextid: '2',
    assetid: '5707630185',
    classid: '310777105',
    instanceid: '302028390',
    amount: 1,
    pos: 10,
    id: '5707630185',
    background_color: '',
    icon_url: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot6-iFBRv7ODcfi9P6s65mpS0mvLwOq7c2D5QvsN12OqWoNX33ATm8xBpYGrzctKSdlNqZgzR-QXole_u1sC16czXiSw0a5jTWaU',
    icon_url_large: '-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot6-iFBRv7ODcfi9P6s65mpS0mvLwOq7cqWdQ-sJ0xLzAo4rx2lfj_ko-Z2nxLNWQcQU-NwzX_gTqxrruhsLq6JzImiRq73E8pSGKGKM1zdg',
    descriptions: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    tradable: true,
    actions: [ [Object] ],
    name: 'AUG | Storm',
    name_color: 'D2D2D2',
    type: 'Consumer Grade Rifle',
    market_name: 'AUG | Storm (Field-Tested)',
    market_hash_name: 'AUG | Storm (Field-Tested)',
    market_actions: [ [Object] ],
    commodity: false,
    market_tradable_restriction: 7,
    marketable: true,
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    is_currency: false,
    market_marketable_restriction: 0,
    fraudwarnings: [] } ]
